# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 467576ea04878f00f605df77603bbc53ddcc1d23de5962d4ba889618eba88e4f0ab3a2413492319e31e19db332ad14f3c497e48ffa75c2a7ae95d7b18e500748

test:
  secret_key_base: 10e58b9369c7ffba3998ca899a62dec2829dbe5e07d1162a340daf72b890f76fd6a37f6407e07d926ff3f77def196d95d5a9ab8c03855675ac2a262d86b430b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
